# Generated by Django 3.2 on 2021-04-30 18:19

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('details', models.CharField(default='', max_length=100)),
                ('room_desc', models.TextField(default='', max_length=1000)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_cover)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img)),
            ],
        ),
    ]
