# Generated by Django 3.2 on 2021-04-30 18:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img),
        ),
        migrations.AddField(
            model_name='room',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img),
        ),
        migrations.AddField(
            model_name='room',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img),
        ),
    ]
