# Generated by Django 3.2 on 2021-05-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
