# Generated by Django 3.2 on 2021-04-30 19:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210430_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img),
        ),
        migrations.AddField(
            model_name='room',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img),
        ),
        migrations.AddField(
            model_name='room',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img),
        ),
        migrations.AddField(
            model_name='room',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img),
        ),
        migrations.AddField(
            model_name='room',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img),
        ),
        migrations.AddField(
            model_name='room',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path_img),
        ),
    ]
