# Generated by Django 3.2 on 2021-04-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_room_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
