# Generated by Django 3.2 on 2021-04-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_room_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
