# Generated by Django 3.2 on 2021-04-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210430_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Bookings',
        ),
    ]
