# Generated by Django 3.2 on 2021-04-30 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_book_bookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
